# action.yaml
name: 'CCF deployment'
description: 'CCF deployment'
inputs:
  cert: 'MemberCertificate'
    description: 'Input'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cert }}