# action.yaml
name: 'CCF deployment'
description: 'CCF deployment'
inputs:
  ccfurl:
    description: 'The base endpoint for CCF'
    required: true
outputs:
  status:
    description: 'The status of the proposal'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ccfurl }}
