on: [push]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello action
        uses: ./
        id: hello
      - name: Get output
        run: echo "test"