on: [push]

jobs:
  hello_job:
    runs-on: ubuntu-latest
    name: A job to deploy mCCF application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: 'echo "$CERT" > /opt/ccf/bin/cert'
        shell: bash
        env:
          CERT: ${{ secrets.MEMBERCERT }}
      - run: 'echo "$KEY" > /opt/ccf/bin/key'
        shell: bash
        env:
          KEY: ${{ secrets.MEMBERKEY }}
      - name: mCCF deploy action
        uses: ./
        id: deploy