on: [push]

jobs:
  ccf-deploy:
    runs-on: ubuntu-latest
    name: Deploy CCF application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get member cert
        run: 'echo "$CERT" > cert'
        shell: bash
        env:
          CERT: ${{ secrets.MEMBERCERT }}
      - name: Get member key
        run: 'echo "$KEY" > key'
        shell: bash
        env:
          KEY: ${{ secrets.MEMBERKEY }}
      - name: mCCF deploy action
        uses: ./
        id: deploy
      - name: Get the proposal id
        run: echo "The proposal id is ${{ steps.deploy.outputs.proposal }}"