on: [push]

jobs:
  ccf-deploy:
    runs-on: ubuntu-latest
    name: Deploy CCF application
    env:
      CCF_URL: 'https://identitylogapp.confidential-ledger.azure.com/'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get member cert
        run: 'echo "$CERT" > actions/deploy/cert && echo "$CERT" > actions/vote/cert'
        shell: bash
        env:
          CERT: ${{ secrets.MEMBERCERT }}
      - name: Get member key
        run: 'echo "$KEY" > actions/deploy/key && echo "$KEY" > actions/vote/key'
        shell: bash
        env:
          KEY: ${{ secrets.MEMBERKEY }}
      - name: mCCF deploy action
        uses: ./actions/deploy
        id: deploy
        env:
          CERTD: ${{ secrets.MEMBERCERT }}
          KEYD: ${{ secrets.MEMBERKEY }}
        with:
          application: 'actions/deploy/set_js_app.json'
      - name: Get the proposal id
        run: echo "The proposal id is ${{ steps.deploy.outputs.proposal }}"
      - name: mCCF approve action
        uses: ./actions/vote
        id: vote
        env:
          CERTD: ${{ secrets.MEMBERCERT }}
          KEYD: ${{ secrets.MEMBERKEY }}
        with:
          proposal: ${{ steps.deploy.outputs.proposal }}
      - name: Get the status
        run: echo "The proposal id is ${{ steps.vote.outputs.status }}"