on: [push]

jobs:
  ccf-deploy:
    runs-on: ubuntu-latest
    name: Deploy CCF application
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get member cert
        run: 'echo "$CERT" > actions/deploy/cert'
        shell: bash
        env:
          CERT: ${{ secrets.MEMBERCERT }}
      - name: Get member key
        run: 'echo "$KEY" > actions/deploy/key'
        shell: bash
        env:
          KEY: ${{ secrets.MEMBERKEY }}
      - name: mCCF approve action
        uses: ./actions/vote
        id: vote
      - name: Get the status
        run: echo "The proposal id is ${{ steps.vote.outputs.status }}"